In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [3]:
print(type(arr1))  #see the type

<class 'numpy.ndarray'>


In [4]:
arr1   #look it's a numpy array

array([1, 2, 3, 4])

### getting 2D array

In [5]:
myMat = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(myMat)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# same as range() of python

arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((3))

array([1., 1., 1.])

In [23]:
np.linspace(3,20,40)   #returns a 1D vector denoted by the [---]

array([ 3.        ,  3.43589744,  3.87179487,  4.30769231,  4.74358974,
        5.17948718,  5.61538462,  6.05128205,  6.48717949,  6.92307692,
        7.35897436,  7.79487179,  8.23076923,  8.66666667,  9.1025641 ,
        9.53846154,  9.97435897, 10.41025641, 10.84615385, 11.28205128,
       11.71794872, 12.15384615, 12.58974359, 13.02564103, 13.46153846,
       13.8974359 , 14.33333333, 14.76923077, 15.20512821, 15.64102564,
       16.07692308, 16.51282051, 16.94871795, 17.38461538, 17.82051282,
       18.25641026, 18.69230769, 19.12820513, 19.56410256, 20.        ])

In [25]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
#checking the version 
print(np.__version__)

1.20.2


In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)  #checking the dimension of the arrays
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


### Indexing 

In [10]:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


In [11]:
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("every other  from from the array is :")
print(arr[::2])

every other  from from the array is :
[1 3 5 7]


In [13]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [14]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])  #from both indexes return the 2nd indexed element

[3 8]


In [15]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## array of random numbers

In [27]:
np.random.rand(3)   #from[0,1) uniformly distributed

array([0.1077694 , 0.83361752, 0.73116127])

In [30]:
np.random.rand(2,3)   #instead of passing the tuple we'll simply pass the dimensions (unlike other functions that                          we've used)

array([[0.32541218, 0.28070835, 0.51291712],
       [0.85015069, 0.79396885, 0.07688113]])

### this would return numbers from a standard deviation centered around zero

In [32]:
np.random.randn(3)

array([-0.08365237, -0.63774907,  1.05752275])

In [33]:
np.random.randn(3,3)

array([[-1.18989698,  1.66694069, -0.69838534],
       [-0.03112169,  0.8779237 , -0.79866694],
       [ 1.30712798, -1.01654245,  0.88843453]])

# randint

In [35]:
np.random.randint(1,20)   #will give you random number from specified low--high range

16

In [38]:
np.random.randint(1,40,20)    #lowest being inclusive and highest being exclusive

array([13, 38, 14, 33,  5, 19, 31,  1, 19, 12,  6, 11, 30, 23, 35, 29,  5,
       23, 33, 37])

In [39]:
# so here is the use case 
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
ranarr = np.random.randint(1,30,5)
ranarr 

array([22,  6, 20,  8, 11])

# view and copy 

In [43]:
arrCopy = arr.copy()
arrView = arr.view()


In [44]:
arrCopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
arrView

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
# any changes to view or to original array will be reflected in original array and to view 

In [47]:
arrView[0] = -99
arr 

array([-99,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [48]:
arrCopy[1] = 100
arr 

array([-99,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [49]:
arrCopy

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

### reshaping the arrays

In [61]:
ReshapedArr = arr.reshape(4,5)               #size for reshaping should be compatible and all

In [62]:
ReshapedArr

array([[-99,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [63]:
ReshapedArr[0][0]= 1000
ReshapedArr

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19]])

In [65]:
arr            #see the reshape method creates a view of the original array not a copy

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

### getting the max and min value from the array  

In [66]:
ranarr

array([22,  6, 20,  8, 11])

In [67]:
ranarr.max()

22

In [68]:
ranarr.argmax() #would return the index of the max value in the array 

0

In [69]:
ranarr.min()

6

In [70]:
ranarr.argmin()

1

### Getting the shape of the array

## Shape
- The shape of an array is the number of elements in each dimension.

 

In [72]:
ranarr.shape

(5,)

In [75]:
arr.shape

(20,)

In [76]:
arrView.shape 

(20,)

In [112]:
ReshapedArr

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19]])

In [114]:
ReshapedArr.shape    #this says the array has 4 dimension and 5 elements in each dimension

(4, 5)

In [78]:
ReshapedArr.dtype

dtype('int32')

In [82]:
from numpy.random import rand,randint,randn

In [84]:
rand(3,2)

array([[0.82573611, 0.60143357],
       [0.65444135, 0.02244198],
       [0.33379907, 0.18026321]])

In [85]:
randn(2,3)

array([[ 1.40810914, -1.27229768,  0.11301576],
       [ 2.28569152, -1.06317256, -0.13104661]])

In [86]:
randint(4)

3

In [88]:
randint(3,20)

4

In [90]:
randint(2,10,20)

array([4, 2, 3, 2, 7, 7, 6, 6, 3, 3, 5, 5, 8, 8, 7, 8, 3, 6, 2, 7])

# dtype in Numpy

#### By default Python have these data types:

```
strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j
```

#### following are some extra data types supported in Numpy 
```
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
```

In [94]:
arr = np.array([1, 2, 3, 4], dtype='i4')  # Create an array with data type 4 bytes integer:
arr 

array([1, 2, 3, 4])

In [95]:
arr.dtype

dtype('int32')

In [96]:
arr = np.array([1, 2, 3, 4])
arr.dtype 

dtype('int32')

In [99]:
arr = np.array([1, 2, 3, 4], dtype='f') 

In [100]:
arr.dtype 

dtype('float32')

In [102]:
arr = np.array([1, 2, 3, 4], dtype='S')
 


In [103]:
arr 

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [104]:
arr.dtype

dtype('S1')

In [107]:
# arr = np.array(['a', '2', '3'], dtype='i')  #not possible 

# changing the data types 

In [109]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [110]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [111]:
arr.base

In [117]:
print(arr.reshape(3,1).base)

[1 0 3]


## Flattening array means converting a multidimensional array into a 1D array.

- We can use reshape(-1) to do this.

In [118]:
arr = np.array([[1,2,3],[5,66,55],[5,43,21]])

In [119]:
arr 

array([[ 1,  2,  3],
       [ 5, 66, 55],
       [ 5, 43, 21]])

In [120]:
arr.reshape(-1)

array([ 1,  2,  3,  5, 66, 55,  5, 43, 21])

In [121]:
arr 

array([[ 1,  2,  3],
       [ 5, 66, 55],
       [ 5, 43, 21]])

In [122]:
arr_2d = np.arange(20).reshape(4,5)

In [123]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])