# Numpy operations
- array with array 
- array with scalar 
- universal array functions 

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
arr + arr #see elementwise addition took place

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
arr * arr 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
try :
    print(arr/arr)
except :
    print("division by zero not possible")    

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
<ipython-input-8-6b2b87a239a1>:2: RuntimeWarning: invalid value encountered in true_divide
  print(arr/arr)


In [9]:
arr **2 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [10]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [11]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [12]:
np.max(arr)

10

In [13]:
arr.max()

10

In [14]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [15]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

# Appending in numpy array


In [1]:
## Horitzontal Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [2]:
## Vertical Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [4]:
np.append(f,g)  #default is horizontal append

array([1, 2, 3, 4, 5, 6])

# splitting the array

In [11]:
arr = np.arange(1,41)
np.array_split(arr,3)  # We use array_split() for splitting arrays, we pass it the                   # want to split and the number of splits.

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]),
 array([28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])]

In [16]:
#np.split(arr,3)  # for using the split method equla division is 
np.split(arr,2)

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40])]

# Searching in Numpy array

In [20]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

In [24]:
x = np.where(arr==4)
x    # where returns the indexes that get a match.

(array([3, 5, 6], dtype=int64),)

In [26]:
y = np.where(arr%2==0)
y

(array([1, 3, 5, 6], dtype=int64),)

# Sorting numpy array

In [27]:
np.sort(arr)

array([1, 2, 3, 4, 4, 4, 5])

In [28]:
# then comes filter which we've already discussed