# indexing and selection 

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[1]

1

In [6]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

In [8]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [9]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[:3] = 10  #would broadcast this value to all the indexes specified

In [13]:
arr

array([10, 10, 10,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr[:]

array([10, 10, 10,  3,  4,  5,  6,  7,  8,  9, 10])

## slicing also creates a view of the original array 

In [15]:
arr = np.arange(0,11)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr2 = arr[:4]

In [17]:
arr2

array([0, 1, 2, 3])

In [18]:
arr2[:2] = 20
arr2 

array([20, 20,  2,  3])

In [20]:
arr  #see we'were working on the view of the arr till now !

array([20, 20,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## if you want a copy then you can specify it explicitly 

In [22]:
arr2 = arr.copy()
arr2 

array([20, 20,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr_2d = np.array([[10,15,20],[25,30,40],[45,50,55]])

In [25]:
arr_2d

array([[10, 15, 20],
       [25, 30, 40],
       [45, 50, 55]])

In [26]:
arr_2d[0]

array([10, 15, 20])

In [27]:
arr_2d[2][1]

50

## that was the double bracket notation 

In [28]:
# mostly used is comma separated notation 

In [30]:
arr_2d[1,2]    #recommended

40

In [31]:
# grabbing a part 
arr_2d

array([[10, 15, 20],
       [25, 30, 40],
       [45, 50, 55]])

In [34]:
hehe = arr_2d[:2,1:]         #simple just a fluke logic

In [35]:
hehe 

array([[15, 20],
       [30, 40]])

In [37]:
hehe.base    #this is a view 

array([[10, 15, 20],
       [25, 30, 40],
       [45, 50, 55]])

In [38]:
haha = arr_2d.copy()
haha 

array([[10, 15, 20],
       [25, 30, 40],
       [45, 50, 55]])

In [40]:
haha.base #since there is no base for this it is independent 

## conditional selection or filtering

In [41]:
arr = np.arange(0,11)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
b1 = arr>3
b1 

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [44]:
arr[b1]       #use the [] not the ()

array([ 4,  5,  6,  7,  8,  9, 10])

In [46]:
# arr[arr>6 and arr<8]
arr[arr>6 ]

array([ 7,  8,  9, 10])

### splitting the numpy array 

In [50]:
arr = np.array([1, 2, 3, 4, 5, 6])
# array_split method
newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [51]:
# If the array has less elements than required, it will adjust from the end accordingly.
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


####  We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

In [53]:
# splitting 2d array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
# into three 2d array
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


### Split the 2-D array into three 2-D arrays along rows.



In [55]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [56]:
# An alternate solution is using hsplit() opposite of hstack()
# Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## Searching and sorting in array

### search using the np.where(condition) method 

In [59]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)  #prints where the indexes of even numbers

(array([1, 3, 5, 7], dtype=int64),)


### sorting the np array using sort() method

In [62]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr)) # This method returns a copy of the array, leaving the original array unchanged.

[0 1 2 3]


In [63]:
arr 

array([3, 2, 0, 1])

In [64]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [65]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


### sorting 2d arrays  

#### If you use the sort() method on a 2-D array, both arrays will be sorted:

In [67]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Numpy operations